apiVersion: v1
kind: Service
metadata:
  name: frontend-svc
  namespace: expertlab
spec:
  selector:
    app: frontend-camels
  ports:
  - name: frontend-port
    port: 80 
    targetPort: 80 
    protocol: TCP
  type: ClusterIP

---

apiVersion: v1
kind: Service
metadata:
  name: backend-svc
  namespace: expertlab
spec:
  selector:
    app: backend-camels
  ports:
  - name: backend-port
    port: 3000 
    targetPort: 3000 
    protocol: TCP
  type: ClusterIP