apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: camels-argo-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/SandroBarillaPXL/expertlab-sprint4-kubernetes.git
    path: k8s
  destination: 
    server: https://kubernetes.default.svc
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: false #true to auto sync live cluster to repo state
      prune: true