apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: camels-hpa
  namespace: expertlab
spec:
  maxReplicas: 9
  minReplicas: 3
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: frontend-camels
  targetCPUUtilizationPercentage: 2