apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: locust
  name: locust-worker
  labels:
    name: locust-worker
spec:
  replicas: 2
  selector:
    matchLabels:
      app: locust-worker
  template:
    metadata:
      labels:
        app: locust-worker
    spec:
      containers:
        - name: locust-worker
          image: sandropxl/locust:expertlab4
          env:
            - name: LOCUST_MODE
              value: worker
            - name: LOCUST_MASTER_URL
              value: locust-master
            - name: TARGET_HOST
              value: http://frontend-svc.expertlab.svc.cluster.local
